import { useState } from "react";
import type { FormEvent } from "react";
import {
  ArrowRight,
  BookOpen,
  Camera,
  ChevronDown,
  HeartHandshake,
  HelpCircle,
  Loader2,
  ScanLine,
  ShieldCheck,
  Star,
} from "lucide-react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { api, errorMessage } from "../services/api";
import { Badge, ErrorNotice, PageHeading } from "../components/Common";
import { Button } from "../components/ui/button";

const help = [
  [
    "What is VisionOps AI?",
    "VisionOps AI finds common objects in photos and shows where they are. It also helps your team revisit results, monitor service activity, and report predictions that need a human review. The pretrained YOLO11n model recognizes 80 common categories; it does not identify individual people.",
  ],
  [
    "How do I analyze an image?",
    "Open Analyze, then drag a photo into the upload area or choose an image from your device. Check the preview and select Analyze image. You can use JPEG, PNG, and WebP files up to 10 MB and 20 megapixels. The optional sample collection is a convenient place to start.",
  ],
  [
    "How does camera capture work?",
    "Choose Camera and enable camera access when your browser asks. Position your subject, then select Capture image. Only the captured still image is sent when you select Analyze. Video stays in your browser. If permission is denied or the camera is busy, use image upload instead. Camera access requires localhost or HTTPS.",
  ],
  [
    "What are the boxes around objects?",
    "Each box marks the area where the model believes an object is located. The label shows its category and confidence. Boxes can overlap, miss an object, or include too much background. Use Original image to compare the result with your photo.",
  ],
  [
    "What does confidence mean?",
    "Confidence indicates how strongly the model associates a box with a category. A 90% score is not a guarantee that the prediction is right, and is not a full explanation of the model’s reasoning. Raising the confidence threshold hides less confident detections; lowering it may reveal more objects and more mistakes.",
  ],
  [
    "Where can I find previous predictions?",
    "Employees can open Prediction history to revisit their own images and results. Administrators can review predictions across the workspace. Search by object, filename, or prediction ID, or filter by date, confidence, status, and feedback. Guests can see their current results but cannot browse history.",
  ],
  [
    "How do I report an incorrect prediction?",
    "Sign in as an employee or administrator, open a result, and choose Incorrect. Select a reason, optionally add context, and submit. A reviewer can inspect the original image, detections, and model version. Reports do not automatically change or retrain the model.",
  ],
  [
    "Why did the model find no objects?",
    "The image may contain categories outside the 80 COCO classes, objects may be too small or obscured, or the threshold may be too high. Try a well-lit image with a clear subject or reduce the threshold. No detections is a valid result, not a service error.",
  ],
  [
    "What happens to my images?",
    "Images are saved in this server’s local application data directory so authorized users can review results. Image metadata such as EXIF GPS is removed during re-encoding. Your own employee images are visible to you and administrators. Guest images are also retained and visible to administrators; do not upload sensitive material. There is no automatic deletion schedule yet.",
  ],
  [
    "What is the difference between demo and live data?",
    "Seeded history has a Demo label and illustrative historical timestamps. Its detections are generated by the real model during setup. A separate optional synthetic demo mode uses fixed development responses and is clearly labeled. Choose Live only in analytics or history to exclude all demo records.",
  ],
  [
    "What do Analytics and Model performance show?",
    "Analytics shows how the service is running: request volumes, latency, errors, and confidence distribution. Model performance shows published benchmark information and explains which quality metrics have not been evaluated here. Human feedback counts are useful review signals, not measured accuracy.",
  ],
  [
    "The service is unavailable. What should I do?",
    "Check that the backend is running at port 8000 and the frontend at port 5173. An administrator can check System health. If the model is unavailable, run the documented model setup command and restart the backend. You can retry after the service is healthy.",
  ],
];
export function Help() {
  return (
    <>
      <PageHeading
        eyebrow="HELP & DOCUMENTATION"
        title="A little guidance. A clearer view."
        description="Everything you need to get from your first image to a useful insight."
        actions={
          <Badge>
            <BookOpen size={14} />
            Getting started
          </Badge>
        }
      />
      <div className="help-intro-grid">
        {[
          {
            icon: ScanLine,
            title: "Your first analysis",
            text: "Upload, analyze, and explore your detections.",
            link: "/analyze",
            action: "Open workspace",
          },
          {
            icon: Camera,
            title: "Capture a moment",
            text: "Use your camera to analyze the world around you.",
            link: "/analyze",
            action: "Try camera capture",
          },
          {
            icon: ShieldCheck,
            title: "Human perspective matters",
            text: "Model predictions can be wrong. Your feedback adds context.",
            link: "#help-6",
            action: "Learn about review",
          },
        ].map((c) => (
          <section className="card help-intro" key={c.title}>
            <c.icon size={25} />
            <h3>{c.title}</h3>
            <p>{c.text}</p>
            {c.link.startsWith("#") ? (
              <a className="text-link" href={c.link}>
                {c.action}
                <ArrowRight size={14} />
              </a>
            ) : (
              <Link className="text-link" to={c.link}>
                {c.action}
                <ArrowRight size={14} />
              </Link>
            )}
          </section>
        ))}
      </div>
      <section className="help-body">
        <div>
          <span className="eyebrow">GOOD QUESTIONS</span>
          <h2>Let’s make it simple.</h2>
          <p>
            A practical guide to understanding the workspace and your results.
          </p>
          <div className="help-tip">
            <HelpCircle size={20} />
            <p>
              Use a clear photo with everyday objects for the best first
              experience.
            </p>
          </div>
        </div>
        <div className="help-accordions">
          {help.map(([q, a], i) => (
            <details id={`help-${i}`} key={q} open={i === 0}>
              <summary>
                {q}
                <ChevronDown size={16} />
              </summary>
              <p>{a}</p>
            </details>
          ))}
        </div>
      </section>
    </>
  );
}
export function Feedback() {
  const [rating, setRating] = useState(4);
  const [category, setCategory] = useState("Feature request");
  const [message, setMessage] = useState("");
  const [prediction, setPrediction] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [sent, setSent] = useState(false);
  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      await api("/api/feedback", {
        method: "POST",
        body: JSON.stringify({
          rating,
          category,
          message,
          prediction_id: prediction.trim() || null,
        }),
      });
      setSent(true);
      toast.success("Feedback received. Thank you.");
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setBusy(false);
    }
  };
  return (
    <>
      <PageHeading
        eyebrow="YOUR PERSPECTIVE"
        title="Help us see what’s missing."
        description="A better workspace starts with the people who use it."
      />
      <div className="feedback-page-grid">
        <section className="card feedback-form-card">
          {sent ? (
            <div className="feedback-success">
              <HeartHandshake size={42} />
              <h2>We’re glad you shared.</h2>
              <p>
                Your feedback is saved and available to workspace
                administrators.
              </p>
              <Button
                variant="outline"
                onClick={() => {
                  setSent(false);
                  setMessage("");
                  setPrediction("");
                }}
              >
                Share another thought
              </Button>
            </div>
          ) : (
            <form onSubmit={(e) => void submit(e)}>
              <h2>How’s your experience?</h2>
              <p>Tell us what’s working and what could be better.</p>
              <fieldset className="star-rating">
                <legend>Overall rating</legend>
                {[1, 2, 3, 4, 5].map((n) => (
                  <button
                    type="button"
                    key={n}
                    aria-label={`${n} star${n > 1 ? "s" : ""}`}
                    aria-pressed={rating === n}
                    onClick={() => setRating(n)}
                  >
                    <Star
                      size={30}
                      fill={n <= rating ? "currentColor" : "none"}
                    />
                  </button>
                ))}
                <span>{rating} of 5</span>
              </fieldset>
              <label htmlFor="category">What’s this about?</label>
              <select
                id="category"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
              >
                {[
                  "Incorrect prediction",
                  "UI issue",
                  "Performance issue",
                  "Feature request",
                  "Other",
                ].map((c) => (
                  <option key={c}>{c}</option>
                ))}
              </select>
              <label htmlFor="feedback-message">Your feedback</label>
              <textarea
                id="feedback-message"
                minLength={5}
                maxLength={3000}
                required
                rows={5}
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="A small detail or a big idea — we’re listening."
              />
              <label htmlFor="prediction-reference">
                Prediction ID <span className="muted">(optional)</span>
              </label>
              <input
                id="prediction-reference"
                maxLength={32}
                value={prediction}
                onChange={(e) => setPrediction(e.target.value)}
                placeholder="Paste a prediction ID to add context"
              />
              <small>
                You can copy the full ID from a prediction’s Technical details.
              </small>
              {error && <ErrorNotice message={error} />}
              <Button type="submit" disabled={busy}>
                {busy ? (
                  <Loader2 className="spin" size={16} />
                ) : (
                  <>
                    Send feedback <ArrowRight size={16} />
                  </>
                )}
              </Button>
            </form>
          )}
        </section>
        <aside className="feedback-aside">
          <HeartHandshake size={32} strokeWidth={1.3} />
          <h2>
            Every perspective
            <br />
            makes a difference.
          </h2>
          <p>
            Your feedback helps us understand real experiences and prioritize
            useful improvements.
          </p>
          <div>
            <h3>Reporting a model mistake?</h3>
            <p>
              For a specific incorrect detection, use the Correct / Incorrect
              buttons on that prediction. This keeps your report connected to
              the image and model output.
            </p>
            <Link className="text-link" to="/history">
              Find a prediction <ArrowRight size={15} />
            </Link>
          </div>
          <small>
            Feedback is reviewed by humans. It does not automatically retrain
            the model.
          </small>
        </aside>
      </div>
    </>
  );
}
